services:

  Divante\NotificationsBundle\Controller\ActionController:
    public: true
    tags: [controller.service_arguments]

  Divante\NotificationsBundle\Controller\NotificationController:
    public: true
    tags: [controller.service_arguments]
    
  Divante\NotificationsBundle\Server\NotificationServer:
    public: true
    arguments:
      $serializer: '@pimcore_admin.serializer'

  Divante\NotificationsBundle\Service\ActionService:
    autowire: true
    public: false
    
  Divante\NotificationsBundle\Service\NotificationService:
    autowire: true
    public: false

  Divante\NotificationsBundle\Service\UserService:
    autowire: true
    public: false
